### ISSUE TITLE
Homescreen - With Walks

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#102]
<img width="1801" alt="Screen Shot 2024-04-22 at 7 45 08 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/7b13e425-8374-44fa-9a82-7dd1316d45d1">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5580%3A5979&mode=dev&t=7MqolW38DigQx0q3-1](url)

@francisli

**Comment by francisli** [comment]
No changes
