### ISSUE TITLE
Homescreen - With Walks (Spanish)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#103]
<img width="1805" alt="Screen Shot 2024-04-22 at 7 46 27 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/0de8f96d-1b93-4f89-961b-60d5f2b4a237">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5583%3A8059&mode=dev&t=7MqolW38DigQx0q3-1](url)

@francisli

**Comment by francisli** [comment]
@KelsMarie inconsistent again. Are the titles "Caminata ..." per the slide image above, or "Paseo..." which is in the figma? I'm going to leave them as "Caminata..."

**Comment by francisli** [comment]
If Caminata... is correct, then no changes are needed.
