### ISSUE TITLE
Homescreen - With Walks (Chinese)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#104]
<img width="1813" alt="Screen Shot 2024-04-22 at 7 47 49 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/8883cd57-1c32-49a3-aa9a-b813749b5ad9">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5583%3A8322&mode=dev&t=7MqolW38DigQx0q3-1](url)

@francisli

**Comment by francisli** [comment]
No changes needed
