### ISSUE TITLE
Homescreen Pre Competition Notification - SPANISH

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#106]
<img width="1774" alt="Screen Shot 2024-04-22 at 7 53 16 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/ad511117-88ed-41b8-aadb-1bc269d9f535">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5596%3A3483&mode=dev&t=7MqolW38DigQx0q3-1](url)

@francisli

**Comment by francisli** [comment]
No changes
