### ISSUE TITLE
Homescreen Pre Competition Notification - CHINESE

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#107]
<img width="1795" alt="Screen Shot 2024-04-22 at 7 55 11 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/89206f23-0098-4aee-ad22-dda1dd812752">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5596%3A3599&mode=dev&t=7MqolW38DigQx0q3-1](url)

@francisli

**Comment by francisli** [comment]
No changes
