### ISSUE TITLE
Homescreen Post Competition Notification

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#119]
<img width="1798" alt="Screen Shot 2024-04-29 at 3 04 32 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/155a0bf0-8660-42a4-a46b-53f4e76cf7aa">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5596%3A3715&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
