### ISSUE TITLE
Homescreen post competition notification (Chinese)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#121]
<img width="1783" alt="Screen Shot 2024-04-29 at 3 08 37 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/f20eefde-a590-45cb-a40a-329d5de02eb8">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5597%3A3948&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
