### ISSUE TITLE
Homescreen During Competition Banner

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#122]
<img width="1783" alt="Screen Shot 2024-04-29 at 3 29 23 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/f2f60e2e-37b4-4d14-a19f-574b150a8ae9">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5597%3A4064&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
