### ISSUE TITLE
Current competition banner (Spanish)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#123]
<img width="1786" alt="Screen Shot 2024-04-29 at 3 32 31 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/20a1135a-e589-464a-a60b-136f12a7825f">

[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5601%3A4646&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
