### ISSUE TITLE
During competition banner (Chinese)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#124]
<img width="1796" alt="Screen Shot 2024-04-29 at 3 34 14 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/d639bb3c-6c52-455c-90e0-76513fc03b50">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5597%3A4297&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
