### ISSUE TITLE
No current walking challenge banner

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#125]
<img width="1794" alt="Screen Shot 2024-04-29 at 3 39 32 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/6b59e8fc-dbb0-45b1-b835-dc75fd0e3938">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5598%3A4413&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
