### ISSUE TITLE
No current walking challenge (Spanish)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#126]
<img width="1785" alt="Screen Shot 2024-04-29 at 3 41 18 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/fae20e4f-6ab0-490b-abe6-90141dd9644d">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5597%3A4181&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
