### ISSUE TITLE
No current walking challenge (Chinese)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#127]
<img width="1816" alt="Screen Shot 2024-04-29 at 3 44 14 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/0702055d-87e6-4ed4-aaa2-5045ea1ade8e">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5600%3A4530&mode=dev&t=rSkIraw90nu1o5o7-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #187
