### ISSUE TITLE
My Recorded Walks

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#146]
<img width="1782" alt="Screen Shot 2024-05-01 at 7 48 03 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/68a632c3-7de7-423e-90cc-8de2514871d1">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5609%3A3753&mode=dev&t=iaqdYs95cxJAId6A-1](url)

@francisli

**Comment by francisli** [comment]
No code changes necessary for this
