### ISSUE TITLE
My Recorded Walks (Spanish)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#147]
<img width="1790" alt="Screen Shot 2024-05-01 at 7 50 43 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/5360ab0a-198c-4382-8ce6-158a5996bdfc">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5609%3A3875&mode=dev&t=iaqdYs95cxJAId6A-1](url)

@francisli

**Comment by francisli** [comment]
No code changes necessary for this
