### ISSUE TITLE
iWalk Information (Chinese)

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#151]
<img width="1790" alt="Screen Shot 2024-05-01 at 7 56 56 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/a0b2d0ab-cc73-4865-9fb4-200b6da90b49">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5609%3A6448&mode=dev&t=iaqdYs95cxJAId6A-1](url)

@francisli

**Comment by francisli** [comment]
Closed in #192
