### ISSUE TITLE
User should see the Intentional Walk splash screen on startup

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk-client#3]
Testing on iOS simulator, we're seeing the generic React Native splash screen.

**Comment by markkhoo** [comment]
I tested this on android. The `react-native-splash-screen` package seems to be autolinked to `android/app/src/main/java/com/intentionalwalkclient/MainApplication.java`. However I can't confirm if it works on my android emulator. The app seems to be loading fast enough that I can't see the splash screen.

**Comment by francisli** [comment]
The splash screen resources still need to be copied from the sfbrigade/intentional-walk project into this new project.

I'd also suggest switching from react-native-splash-screen, which hasn't been updated in years, to expo-splash-screen: https://www.npmjs.com/package/expo-splash-screen

**Comment by francisli** [comment]
Instead of the Expo package, which requires installing more Expo dependencies, let's try this one:

https://www.npmjs.com/package/react-native-bootsplash
