### ISSUE TITLE
Onboarding sign up -Chinese updated

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#55]
<img width="1823" alt="Screen Shot 2024-04-07 at 4 09 02 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/d5e5a68a-051c-4e30-a411-4676c5d3aaee">

https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5426%3A4499&mode=dev&t=DsBptfTZeiMYVdFo-1
@francisli

**Comment by francisli** [comment]
@KelsMarie in English, the text next to the checkbox is "By signing up, I agree to the _Privacy Policy_ and _Contest Rules_." where Privacy Policy and Contest Rules are each separately linked to the corresponding texts.

In this new translation for the checkbox string, it appears to reference Privacy Policy but NOT Contest rules. The current string we display is:

簽署即表示我同意**隱私條款**和**官方程序規則**.
