### ISSUE TITLE
Valid Zip Code Overlay - English

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#71]
<img width="1816" alt="Screen Shot 2024-04-15 at 1 34 02 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/74f0326f-ff20-441a-b562-fd682481ee4d">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5582%3A7713&mode=dev&t=CB34CJgl3TkBnUUW-1](url)

@francisli

**Comment by francisli** [comment]
The app already uses this exact text.
