### ISSUE TITLE
Valid Zip Code - Spanish

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#72]
<img width="1811" alt="Screen Shot 2024-04-15 at 1 40 12 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/153914cf-a3ed-48d0-b74f-b7446eb62e52">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5582%3A7641&mode=dev&t=CB34CJgl3TkBnUUW-1](url)

@francisli

**Comment by KelsMarie** [comment]
https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5582%3A7641&mode=dev&t=CB34CJgl3TkBnUUW-1

**Comment by francisli** [comment]
The app already uses this exact text.

**Comment by francisli** [comment]
@KelsMarie this is another example of things being a bit out of sync- the image pasted in this issue shows the text "Debe ser..." but in the Figma link, the text is "Debes ser"... I'll assume it's the latter...
