### ISSUE TITLE
Valid Zip Code - Chinese

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#73]
<img width="1803" alt="Screen Shot 2024-04-15 at 1 42 22 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/ee782cf8-02ba-4204-b1dc-ed91c02546f0">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=5582%3A7785&mode=dev&t=CB34CJgl3TkBnUUW-1](url)

@francisli

**Comment by francisli** [comment]
The app already uses this exact text.
