### ISSUE TITLE
Onboarding - Done Signing 

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk-client#86]
<img width="1797" alt="Screen Shot 2024-04-21 at 4 10 31 PM" src="https://github.com/sfbrigade/intentional-walk-client/assets/55925894/2686f99f-6b75-4c5d-9fff-1406491b6089">
[https://www.figma.com/file/Ne0LN7fS6sQR3sMP96GDes/Code-for-SF-%2B-Intentional-Walk?type=design&node-id=4963%3A7108&mode=dev&t=5dN7YnOSoolCap6O-1](url)

@francisli

**Comment by francisli** [comment]
@KelsMarie just FYI the Figma is not in sync with the changes in the slide image above. I will copy the changes from the slide image.
